spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 0
